Chore/response headers (#59)
* Chore: replace header parsing with module

Fixes `Audit error: (cookie || "").split is not a function` error.

* Refactor response headers to GET

* correct name from RequestHeaders.
* use request instead of request-promise to access response headers.
* update all references.

Fixes #51.